# Generated by Django 6.0.3 on 2026-04-16 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('test', '0002_rename_article_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='content',
        ),
        migrations.AddField(
            model_name='test',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='category.category'),
        ),
        migrations.AlterField(
            model_name='test',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='TestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_type', models.CharField(choices=[('One right', 'One Right'), ('Multy right', 'Multy Right'), ('True/False', 'Boolean')], default='One right', max_length=11)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.test')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('test_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.testitem')),
            ],
        ),
    ]
